services:
  db:
    image: postgres:16-alpine
    container_name: exphub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: exphub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d exphub"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - exphub-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exphub-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_MODE: docker
      BANK_BASE_URL: http://exphub-mock-bank:8000
      BANK_PUBLIC_BASE_URL: http://exphub-backend:8080
      DB_DOCKER_URL: jdbc:postgresql://db:5432/exphub
      DB_USER: postgres
      DB_PASSWORD: password
      LIQUIBASE_ENABLED: "true"
      HIBERNATE_HBM2DDL_AUTO: validate
      LOG_DIR: /usr/local/tomcat/logs/app
    ports:
      - "8080:8080"
    volumes:
      - ./storage/uploads:/usr/local/tomcat/storage/uploads
      - ./logs:/usr/local/tomcat/logs/app
    secrets:
      - jwt_public_key
      - jwt_private_key
    networks:
      - exphub-network

secrets:
  jwt_public_key:
    file: ./data/secrets/public.pem
  jwt_private_key:
    file: ./data/secrets/private.pem

volumes:
  postgres-data:

networks:
  exphub-network:
    driver: bridge