app.mode=${APP_MODE:docker}

db.web.url=${DB_WEB_URL:jdbc:postgresql://localhost:5433/bookstore_db}
db.docker.url=${DB_DOCKER_URL:jdbc:postgresql://db:5432/bookstore_db}
db.user=${DB_USER:postgres}
db.password=${DB_PASSWORD:psql_password}

hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=${HIBERNATE_HBM2DDL_AUTO:validate}

liquibase.enabled=${LIQUIBASE_ENABLED:true}
liquibase.change-log=${LIQUIBASE_CHANGE_LOG:classpath:db/changelog/db.changelog-master.yaml}

app.admin.email=${APP_ADMIN_EMAIL:admin@ya.ru}
app.admin.password=${APP_ADMIN_PASSWORD:12345}

jwt.expiration=${JWT_EXPIRATION:PT10M}
jwt.refresh_token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION:P30D}

activity.cancellation.min_hours_before_start=${ACTIVITY_CANCELLATION_MIN_HOURS_BEFORE_START:24}
booking.expires-minutes=${BOOKING_EXPIRES_MINUTES:15}

media.docker.storage.root_path=${MEDIA_DOCKER_STORAGE_ROOT_PATH:./storage/uploads}
media.web.storage.root_path=${MEDIA_WEB_STORAGE_ROOT_PATH:app/storage/uploads}
media.files.storage.max_size_bytes=${MEDIA_FILES_STORAGE_MAX_SIZE_BYTES:10485760}
media.videos.storage.max_size_bytes=${MEDIA_VIDEOS_STORAGE_MAX_SIZE_BYTES:524288000}
media.videos.default.chunk_size_bytes=${MEDIA_VIDEOS_DEFAULT_CHUNK_SIZE_BYTES:1048576}
media.playback.token.secret=${MEDIA_PLAYBACK_TOKEN_SECRET:secret-key}
media.playback.token.ttl_seconds=${MEDIA_PLAYBACK_TOKEN_TTL_SECONDS:360}

secrets.docker.public_key=${SECRETS_DOCKER_PUBLIC_KEY:/run/secrets/jwt_public_key}
secrets.docker.private_key=${SECRETS_DOCKER_PRIVATE_KEY:/run/secrets/jwt_private_key}
secrets.web.public_key=${SECRETS_WEB_PUBLIC_KEY:./data/secrets/public.pem}
secrets.web.private_key=${SECRETS_WEB_PRIVATE_KEY:./data/secrets/private.pem}
